import "/src/dept/dept.graphql.ts";
import "/src/menu/menu.graphql.ts";
import "/src/tenant/tenant.graphql.ts";
import "/src/usr/usr.graphql.ts";
import "/src/dict_detail/dict_detail.graphql.ts";
import "/src/dictbiz_detail/dictbiz_detail.graphql.ts";
import "/src/i18n/i18n.graphql.ts";
import "/src/options/options.graphql.ts";
import "/src/lang/lang.graphql.ts";
