import "/src/base/dept/dept.graphql.ts";
import "/src/base/menu/menu.graphql.ts";
import "/src/base/tenant/tenant.graphql.ts";
import "/src/base/usr/usr.graphql.ts";
import "/src/base/dict_detail/dict_detail.graphql.ts";
import "/src/base/dictbiz_detail/dictbiz_detail.graphql.ts";
import "/src/base/i18n/i18n.graphql.ts";
import "/src/base/options/options.graphql.ts";
import "/src/base/lang/lang.graphql.ts";
