schema:
  - './src/common/gql/base.graphql'
  - './src/common/gql/schema.graphql'
generates:
  ../pc/src/typings/types.ts:
    plugins:
      - typescript
      - typescript-operations
    config:
      useTypeImports: true
      scalars:
        Decimal: string
        BigDecimal: string
        Date: string
        DateTime: string
        NaiveDate: string
        NaiveDateTime: string
        NaiveTime: string
        JSON: string
        Uuid: string
  ../uni/src/typings/types.ts:
    plugins:
      - typescript
      - typescript-operations
    config:
      useTypeImports: true
      scalars:
        Decimal: string
        BigDecimal: string
        Date: string
        DateTime: string
        NaiveDate: string
        NaiveDateTime: string
        NaiveTime: string
        JSON: string
        Uuid: string
