nodeLinker: hoisted
allowBuilds:
  "cpu-features": true
  "sharp": true
  "ssh2": true
supportedArchitectures:
  os:
    - linux
    - current
  cpu:
    - x64
    - current
minimumReleaseAgeExclude:
  - dayjs@1.11.21
  - mysql2@3.22.4
