/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppLoading: typeof import('./../components/AppLoading/AppLoading.vue')['default']
    CustomSelect: typeof import('./../components/CustomSelect/CustomSelect.vue')['default']
    CustomSelectModal: typeof import('./../components/CustomSelectModal/CustomSelectModal.vue')['default']
    DictSelect: typeof import('./../components/DictSelect/DictSelect.vue')['default']
    DictbizSelect: typeof import('./../components/DictbizSelect/DictbizSelect.vue')['default']
    CustomInput: typeof import('./../components/CustomInput/CustomInput.vue')['default']
    CustomDivider: typeof import('./../components/CustomDivider/CustomDivider.vue')['default']
    CustomIcon: typeof import('./../components/CustomIcon/CustomIcon.vue')['default']
    TmAlert: typeof import('./../uni_modules/tm-ui/components/tm-alert/tm-alert.vue')['default']
    TmBadge: typeof import('./../uni_modules/tm-ui/components/tm-badge/tm-badge.vue')['default']
    TmBetweenTime: typeof import('./../uni_modules/tm-ui/components/tm-between-time/tm-between-time.vue')['default']
    TmButton: typeof import('./../uni_modules/tm-ui/components/tm-button/tm-button.vue')['default']
    TmCell: typeof import('./../uni_modules/tm-ui/components/tm-cell/tm-cell.vue')['default']
    TmCheckbox: typeof import('./../uni_modules/tm-ui/components/tm-checkbox/tm-checkbox.vue')['default']
    TmCheckboxGroup: typeof import('./../uni_modules/tm-ui/components/tm-checkbox-group/tm-checkbox-group.vue')['default']
    TmCol: typeof import('./../uni_modules/tm-ui/components/tm-col/tm-col.vue')['default']
    TmCollapse: typeof import('./../uni_modules/tm-ui/components/tm-collapse/tm-collapse.vue')['default']
    TmCollapseItem: typeof import('./../uni_modules/tm-ui/components/tm-collapse-item/tm-collapse-item.vue')['default']
    TmDateView: typeof import('./../uni_modules/tm-ui/components/tm-date-view/tm-date-view.vue')['default']
    TmDrawer: typeof import('./../uni_modules/tm-ui/components/tm-drawer/tm-drawer.vue')['default']
    TmEchart: typeof import('./../uni_modules/tm-ui/components/tm-echart/tm-echart.vue')['default']
    TmForm: typeof import('./../uni_modules/tm-ui/components/tm-form/tm-form.vue')['default']
    TmFormItem: typeof import('./../uni_modules/tm-ui/components/tm-form-item/tm-form-item.vue')['default']
    TmHtml: typeof import('./../uni_modules/tm-ui/components/tm-html/tm-html.vue')['default']
    TmIcon: typeof import('./../uni_modules/tm-ui/components/tm-icon/tm-icon.vue')['default']
    TmImage: typeof import('./../uni_modules/tm-ui/components/tm-image/tm-image.vue')['default']
    TmInput: typeof import('./../uni_modules/tm-ui/components/tm-input/tm-input.vue')['default']
    TmModal: typeof import('./../uni_modules/tm-ui/components/tm-modal/tm-modal.vue')['default']
    TmNavbar: typeof import('./../uni_modules/tm-ui/components/tm-navbar/tm-navbar.vue')['default']
    TmPicker: typeof import('./../uni_modules/tm-ui/components/tm-picker/tm-picker.vue')['default']
    TmPickerDate: typeof import('./../uni_modules/tm-ui/components/tm-picker-date/tm-picker-date.vue')['default']
    TmPickerSelected: typeof import('./../uni_modules/tm-ui/components/tm-picker-selected/tm-picker-selected.vue')['default']
    TmPickerView: typeof import('./../uni_modules/tm-ui/components/tm-picker-view/tm-picker-view.vue')['default']
    TmRadio: typeof import('./../uni_modules/tm-ui/components/tm-radio/tm-radio.vue')['default']
    TmRadioGroup: typeof import('./../uni_modules/tm-ui/components/tm-radio-group/tm-radio-group.vue')['default']
    TmRate: typeof import('./../uni_modules/tm-ui/components/tm-rate/tm-rate.vue')['default']
    TmRow: typeof import('./../uni_modules/tm-ui/components/tm-row/tm-row.vue')['default']
    TmSheet: typeof import('./../uni_modules/tm-ui/components/tm-sheet/tm-sheet.vue')['default']
    TmSliderMenu: typeof import('./../uni_modules/tm-ui/components/tm-slider-menu/tm-slider-menu.vue')['default']
    TmStepper: typeof import('./../uni_modules/tm-ui/components/tm-stepper/tm-stepper.vue')['default']
    TmSticky: typeof import('./../uni_modules/tm-ui/components/tm-sticky/tm-sticky.vue')['default']
    TmStickyHeader: typeof import('./../uni_modules/tm-ui/components/tm-sticky-header/tm-sticky-header.vue')['default']
    TmSwitch: typeof import('./../uni_modules/tm-ui/components/tm-switch/tm-switch.vue')['default']
    TmTabs: typeof import('./../uni_modules/tm-ui/components/tm-tabs/tm-tabs.vue')['default']
    TmTag: typeof import('./../uni_modules/tm-ui/components/tm-tag/tm-tag.vue')['default']
    TmText: typeof import('./../uni_modules/tm-ui/components/tm-text/tm-text.vue')['default']
    TmUploadPhoto: typeof import('./../uni_modules/tm-ui/components/tm-upload-photo/tm-upload-photo.vue')['default']
    TmUploadVideo: typeof import('./../uni_modules/tm-ui/components/tm-upload-video/tm-upload-video.vue')['default']
  }
}
