// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppLoading: typeof import('./../components/AppLoading/AppLoading.vue')['default']
    CustomSelect: typeof import('./../components/CustomSelect/CustomSelect.vue')['default']
    CustomInput: typeof import('./../components/CustomInput/CustomInput.vue')['default']
  }
}
