/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppLoading: typeof import('./../components/AppLoading/AppLoading.vue')['default']
    CustomSelect: typeof import('./../components/CustomSelect/CustomSelect.vue')['default']
    CustomInput: typeof import('./../components/CustomInput/CustomInput.vue')['default']
  }
}
