------------------------------------------------------------------------ 流程定义
DROP TABLE IF EXISTS `bpm_process_def`;
CREATE TABLE `bpm_process_def` (
  `id` varchar(22) NOT NULL COMMENT 'ID',
  `img` varchar(22) NOT NULL DEFAULT '' COMMENT '图片',
  `code_seq` int unsigned NOT NULL DEFAULT 0 COMMENT '编码-序列号',
  `code` varchar(45) NOT NULL DEFAULT '' COMMENT '编码',
  `lbl` varchar(100) NOT NULL DEFAULT '' COMMENT '流程名称',
  `category` varchar(45) NOT NULL DEFAULT '' COMMENT '流程分类,dict:bpm_process_def_category',
  `biz_code` ENUM('bpm_test') NOT NULL DEFAULT 'bpm_test' COMMENT '关联业务,dict:bpm_biz_code',
  `current_revision_id` varchar(22) NOT NULL DEFAULT '' COMMENT '当前生效版本',
  `current_revision_id_lbl` varchar(100) NOT NULL DEFAULT '' COMMENT '当前生效版本',
  `is_enabled` tinyint unsigned NOT NULL DEFAULT 1 COMMENT '启用,dict:is_enabled',
  `order_by` int unsigned NOT NULL DEFAULT 1 COMMENT '排序',
  `description` varchar(500) NOT NULL DEFAULT '' COMMENT '流程描述',
  `rem` varchar(100) NOT NULL DEFAULT '' COMMENT '备注',
  `graph_json` json DEFAULT NULL COMMENT '流程图',
  `tenant_id` varchar(22) NOT NULL DEFAULT '' COMMENT '租户',
  `create_usr_id` varchar(22) NOT NULL DEFAULT '' COMMENT '创建人',
  `create_usr_id_lbl` varchar(45) NOT NULL DEFAULT '' COMMENT '创建人',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_usr_id` varchar(22) NOT NULL DEFAULT '' COMMENT '更新人',
  `update_usr_id_lbl` varchar(45) NOT NULL DEFAULT '' COMMENT '更新人',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  `is_deleted` tinyint unsigned NOT NULL DEFAULT 0 COMMENT '删除,dict:is_deleted',
  `delete_usr_id` varchar(22) NOT NULL DEFAULT '' COMMENT '删除人',
  `delete_usr_id_lbl` varchar(45) NOT NULL DEFAULT '' COMMENT '删除人',
  `delete_time` datetime DEFAULT NULL COMMENT '删除时间',
  INDEX (`tenant_id`, `is_deleted`, `lbl`),
  INDEX (`tenant_id`, `is_deleted`, `code`),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_as_cs COMMENT='流程定义';

------------------------------------------------------------------------ 流程版本
DROP TABLE IF EXISTS `bpm_process_revision`;
CREATE TABLE `bpm_process_revision` (
  `id` varchar(22) NOT NULL COMMENT 'ID',
  `process_def_id` varchar(22) NOT NULL DEFAULT '' COMMENT '流程定义',
  `process_def_id_lbl` varchar(100) NOT NULL DEFAULT '' COMMENT '流程定义',
  `lbl` varchar(200) NOT NULL DEFAULT '' COMMENT '名称',
  `process_version` int unsigned NOT NULL DEFAULT 0 COMMENT '版本号',
  `graph_json` json DEFAULT NULL COMMENT '流程图',
  `status` ENUM('published', 'archived') NOT NULL DEFAULT 'published' COMMENT '版本状态,dict:bpm_revision_status',
  `publish_time` datetime DEFAULT NULL COMMENT '发布时间',
  `publish_usr_id` varchar(22) NOT NULL DEFAULT '' COMMENT '发布人',
  `publish_usr_id_lbl` varchar(45) NOT NULL DEFAULT '' COMMENT '发布人',
  `tenant_id` varchar(22) NOT NULL DEFAULT '' COMMENT '租户',
  `create_usr_id` varchar(22) NOT NULL DEFAULT '' COMMENT '创建人',
  `create_usr_id_lbl` varchar(45) NOT NULL DEFAULT '' COMMENT '创建人',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_usr_id` varchar(22) NOT NULL DEFAULT '' COMMENT '更新人',
  `update_usr_id_lbl` varchar(45) NOT NULL DEFAULT '' COMMENT '更新人',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  `is_deleted` tinyint unsigned NOT NULL DEFAULT 0 COMMENT '删除,dict:is_deleted',
  `delete_usr_id` varchar(22) NOT NULL DEFAULT '' COMMENT '删除人',
  `delete_usr_id_lbl` varchar(45) NOT NULL DEFAULT '' COMMENT '删除人',
  `delete_time` datetime DEFAULT NULL COMMENT '删除时间',
  INDEX (`tenant_id`, `is_deleted`, `process_def_id`),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_as_cs COMMENT='流程版本';

------------------------------------------------------------------------ 流程实例
DROP TABLE IF EXISTS `bpm_process_inst`;
CREATE TABLE `bpm_process_inst` (
  `id` varchar(22) NOT NULL COMMENT 'ID',
  `lbl` varchar(200) NOT NULL DEFAULT '' COMMENT '实例标题',
  `process_def_id` varchar(22) NOT NULL DEFAULT '' COMMENT '流程定义',
  `process_def_id_lbl` varchar(100) NOT NULL DEFAULT '' COMMENT '流程定义',
  `process_revision_id` varchar(22) NOT NULL DEFAULT '' COMMENT '流程版本',
  `process_revision_id_lbl` varchar(100) NOT NULL DEFAULT '' COMMENT '流程版本',
  `status` ENUM('running', 'approved', 'rejected', 'revoked') NOT NULL DEFAULT 'running' COMMENT '状态,dict:bpm_inst_status',
  `biz_code` ENUM('bpm_test') NOT NULL DEFAULT 'bpm_test' COMMENT '关联业务,dict:bpm_biz_code',
  `form_data_id` varchar(22) NOT NULL DEFAULT '' COMMENT '业务数据ID',
  `start_usr_id` varchar(22) NOT NULL DEFAULT '' COMMENT '发起人',
  `start_usr_id_lbl` varchar(45) NOT NULL DEFAULT '' COMMENT '发起人',
  `start_dept_id` varchar(22) NOT NULL DEFAULT '' COMMENT '发起人部门',
  `start_dept_id_lbl` varchar(45) NOT NULL DEFAULT '' COMMENT '发起人部门',
  `start_time` datetime DEFAULT NULL COMMENT '发起时间',
  `end_time` datetime DEFAULT NULL COMMENT '结束时间',
  `current_node_ids` json DEFAULT NULL COMMENT '当前活跃节点',
  `current_node_lbls` varchar(500) NOT NULL DEFAULT '' COMMENT '当前节点名称',
  `duration_seconds` int unsigned NOT NULL DEFAULT 0 COMMENT '总耗时(秒)',
  `tenant_id` varchar(22) NOT NULL DEFAULT '' COMMENT '租户',
  `create_usr_id` varchar(22) NOT NULL DEFAULT '' COMMENT '创建人',
  `create_usr_id_lbl` varchar(45) NOT NULL DEFAULT '' COMMENT '创建人',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_usr_id` varchar(22) NOT NULL DEFAULT '' COMMENT '更新人',
  `update_usr_id_lbl` varchar(45) NOT NULL DEFAULT '' COMMENT '更新人',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  `is_deleted` tinyint unsigned NOT NULL DEFAULT 0 COMMENT '删除,dict:is_deleted',
  `delete_usr_id` varchar(22) NOT NULL DEFAULT '' COMMENT '删除人',
  `delete_usr_id_lbl` varchar(45) NOT NULL DEFAULT '' COMMENT '删除人',
  `delete_time` datetime DEFAULT NULL COMMENT '删除时间',
  INDEX (`tenant_id`, `is_deleted`, `lbl`),
  INDEX (`tenant_id`, `is_deleted`, `status`),
  INDEX (`tenant_id`, `is_deleted`, `start_usr_id`),
  INDEX (`tenant_id`, `is_deleted`, `process_def_id`),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_as_cs COMMENT='流程实例';

------------------------------------------------------------------------ 节点实例
DROP TABLE IF EXISTS `bpm_node_inst`;
CREATE TABLE `bpm_node_inst` (
  `id` varchar(22) NOT NULL COMMENT 'ID',
  `process_inst_id` varchar(22) NOT NULL DEFAULT '' COMMENT '流程实例',
  `process_inst_id_lbl` varchar(200) NOT NULL DEFAULT '' COMMENT '流程实例',
  `node_id` varchar(45) NOT NULL DEFAULT '' COMMENT '节点ID',
  `node_type` ENUM('start', 'approve', 'condition', 'parallel', 'end') NOT NULL DEFAULT 'approve' COMMENT '节点类型,dict:bpm_node_type',
  `lbl` varchar(100) NOT NULL DEFAULT '' COMMENT '节点名称',
  `status` ENUM('pending', 'running', 'completed', 'skipped', 'rejected') NOT NULL DEFAULT 'pending' COMMENT '节点状态,dict:bpm_node_inst_status',
  `start_time` datetime DEFAULT NULL COMMENT '开始时间',
  `end_time` datetime DEFAULT NULL COMMENT '结束时间',
  `duration_seconds` int unsigned NOT NULL DEFAULT 0 COMMENT '耗时(秒)',
  `tenant_id` varchar(22) NOT NULL DEFAULT '' COMMENT '租户',
  `create_usr_id` varchar(22) NOT NULL DEFAULT '' COMMENT '创建人',
  `create_usr_id_lbl` varchar(45) NOT NULL DEFAULT '' COMMENT '创建人',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_usr_id` varchar(22) NOT NULL DEFAULT '' COMMENT '更新人',
  `update_usr_id_lbl` varchar(45) NOT NULL DEFAULT '' COMMENT '更新人',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  `is_deleted` tinyint unsigned NOT NULL DEFAULT 0 COMMENT '删除,dict:is_deleted',
  `delete_usr_id` varchar(22) NOT NULL DEFAULT '' COMMENT '删除人',
  `delete_usr_id_lbl` varchar(45) NOT NULL DEFAULT '' COMMENT '删除人',
  `delete_time` datetime DEFAULT NULL COMMENT '删除时间',
  INDEX (`tenant_id`, `is_deleted`, `process_inst_id`),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_as_cs COMMENT='节点实例';

------------------------------------------------------------------------- 任务
DROP TABLE IF EXISTS `bpm_task`;
CREATE TABLE `bpm_task` (
  `id` varchar(22) NOT NULL COMMENT 'ID',
  `lbl` varchar(200) NOT NULL DEFAULT '' COMMENT '任务标题',
  `process_inst_id` varchar(22) NOT NULL DEFAULT '' COMMENT '流程实例',
  `process_inst_id_lbl` varchar(200) NOT NULL DEFAULT '' COMMENT '流程实例',
  `node_inst_id` varchar(22) NOT NULL DEFAULT '' COMMENT '节点实例',
  `node_inst_id_lbl` varchar(100) NOT NULL DEFAULT '' COMMENT '节点实例',
  `assignee_usr_id` varchar(22) NOT NULL DEFAULT '' COMMENT '处理人',
  `assignee_usr_id_lbl` varchar(45) NOT NULL DEFAULT '' COMMENT '处理人',
  `status` ENUM('pending', 'approved', 'rejected', 'transferred', 'revoked') NOT NULL DEFAULT 'pending' COMMENT '任务状态,dict:bpm_task_status',
  `action` ENUM('pending', 'approve', 'reject', 'transfer', 'return', 'add_sign') NOT NULL DEFAULT 'pending' COMMENT '审批动作,dict:bpm_task_action',
  `opinion` varchar(1000) NOT NULL DEFAULT '' COMMENT '审批意见',
  `sign_img` varchar(500) NOT NULL DEFAULT '' COMMENT '手写签名',
  `start_time` datetime DEFAULT NULL COMMENT '任务生成时间',
  `end_time` datetime DEFAULT NULL COMMENT '处理时间',
  `duration_seconds` int unsigned NOT NULL DEFAULT 0 COMMENT '耗时(秒)',
  `is_read` tinyint unsigned NOT NULL DEFAULT 0 COMMENT '已读,dict:yes_no',
  `tenant_id` varchar(22) NOT NULL DEFAULT '' COMMENT '租户',
  `create_usr_id` varchar(22) NOT NULL DEFAULT '' COMMENT '创建人',
  `create_usr_id_lbl` varchar(45) NOT NULL DEFAULT '' COMMENT '创建人',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_usr_id` varchar(22) NOT NULL DEFAULT '' COMMENT '更新人',
  `update_usr_id_lbl` varchar(45) NOT NULL DEFAULT '' COMMENT '更新人',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  `is_deleted` tinyint unsigned NOT NULL DEFAULT 0 COMMENT '删除,dict:is_deleted',
  `delete_usr_id` varchar(22) NOT NULL DEFAULT '' COMMENT '删除人',
  `delete_usr_id_lbl` varchar(45) NOT NULL DEFAULT '' COMMENT '删除人',
  `delete_time` datetime DEFAULT NULL COMMENT '删除时间',
  INDEX (`tenant_id`, `is_deleted`, `assignee_usr_id`, `status`),
  INDEX (`tenant_id`, `is_deleted`, `process_inst_id`),
  INDEX (`tenant_id`, `is_deleted`, `node_inst_id`),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_as_cs COMMENT='审批任务';

--------------------------------------------------------------------------- 转交记录
DROP TABLE IF EXISTS `bpm_transfer`;
CREATE TABLE `bpm_transfer` (
  `id` varchar(22) NOT NULL COMMENT 'ID',
  `task_id` varchar(22) NOT NULL DEFAULT '' COMMENT '原任务',
  `task_id_lbl` varchar(200) NOT NULL DEFAULT '' COMMENT '原任务',
  `from_usr_id` varchar(22) NOT NULL DEFAULT '' COMMENT '转出人',
  `from_usr_id_lbl` varchar(45) NOT NULL DEFAULT '' COMMENT '转出人',
  `to_usr_id` varchar(22) NOT NULL DEFAULT '' COMMENT '接收人',
  `to_usr_id_lbl` varchar(45) NOT NULL DEFAULT '' COMMENT '接收人',
  `reason` varchar(200) NOT NULL DEFAULT '' COMMENT '转交原因',
  `tenant_id` varchar(22) NOT NULL DEFAULT '' COMMENT '租户',
  `create_usr_id` varchar(22) NOT NULL DEFAULT '' COMMENT '创建人',
  `create_usr_id_lbl` varchar(45) NOT NULL DEFAULT '' COMMENT '创建人',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_usr_id` varchar(22) NOT NULL DEFAULT '' COMMENT '更新人',
  `update_usr_id_lbl` varchar(45) NOT NULL DEFAULT '' COMMENT '更新人',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  `is_deleted` tinyint unsigned NOT NULL DEFAULT 0 COMMENT '删除,dict:is_deleted',
  `delete_usr_id` varchar(22) NOT NULL DEFAULT '' COMMENT '删除人',
  `delete_usr_id_lbl` varchar(45) NOT NULL DEFAULT '' COMMENT '删除人',
  `delete_time` datetime DEFAULT NULL COMMENT '删除时间',
  INDEX (`tenant_id`, `is_deleted`, `task_id`),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_as_cs COMMENT='转交记录';

--------------------------------------------------------------------------- 流程日志
DROP TABLE IF EXISTS `bpm_log`;
CREATE TABLE `bpm_log` (
  `id` varchar(22) NOT NULL COMMENT 'ID',
  `process_inst_id` varchar(22) NOT NULL DEFAULT '' COMMENT '流程实例',
  `process_inst_id_lbl` varchar(200) NOT NULL DEFAULT '' COMMENT '流程实例',
  `node_inst_id` varchar(22) NOT NULL DEFAULT '' COMMENT '节点实例',
  `node_inst_id_lbl` varchar(100) NOT NULL DEFAULT '' COMMENT '节点实例',
  `task_id` varchar(22) NOT NULL DEFAULT '' COMMENT '关联任务',
  `task_id_lbl` varchar(200) NOT NULL DEFAULT '' COMMENT '关联任务',
  `action` ENUM('start', 'approve', 'reject', 'transfer', 'return', 'add_sign', 'revoke', 'auto_approve', 'cc', 'end') NOT NULL DEFAULT 'start' COMMENT '动作,dict:bpm_log_action',
  `usr_id` varchar(22) NOT NULL DEFAULT '' COMMENT '操作人',
  `usr_id_lbl` varchar(45) NOT NULL DEFAULT '' COMMENT '操作人',
  `opinion` varchar(1000) NOT NULL DEFAULT '' COMMENT '意见',
  `node_label` varchar(100) NOT NULL DEFAULT '' COMMENT '节点名称',
  `log_time` datetime DEFAULT NULL COMMENT '操作时间',
  `tenant_id` varchar(22) NOT NULL DEFAULT '' COMMENT '租户',
  `create_usr_id` varchar(22) NOT NULL DEFAULT '' COMMENT '创建人',
  `create_usr_id_lbl` varchar(45) NOT NULL DEFAULT '' COMMENT '创建人',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_usr_id` varchar(22) NOT NULL DEFAULT '' COMMENT '更新人',
  `update_usr_id_lbl` varchar(45) NOT NULL DEFAULT '' COMMENT '更新人',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  `is_deleted` tinyint unsigned NOT NULL DEFAULT 0 COMMENT '删除,dict:is_deleted',
  `delete_usr_id` varchar(22) NOT NULL DEFAULT '' COMMENT '删除人',
  `delete_usr_id_lbl` varchar(45) NOT NULL DEFAULT '' COMMENT '删除人',
  `delete_time` datetime DEFAULT NULL COMMENT '删除时间',
  INDEX (`tenant_id`, `is_deleted`, `process_inst_id`),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_as_cs COMMENT='流程日志';
