allowBuilds:
  "@parcel/watcher": true
  "@vue-office/docx": true
  "@vue-office/excel": true
  core-js: true
  es5-ext: true
  "esbuild": true
  "vue-demi": true
minimumReleaseAgeExclude:
  - '@oxlint/binding-android-arm-eabi@1.66.0'
  - '@oxlint/binding-android-arm64@1.66.0'
  - '@oxlint/binding-darwin-arm64@1.66.0'
  - '@oxlint/binding-darwin-x64@1.66.0'
  - '@oxlint/binding-freebsd-x64@1.66.0'
  - '@oxlint/binding-linux-arm-gnueabihf@1.66.0'
  - '@oxlint/binding-linux-arm-musleabihf@1.66.0'
  - '@oxlint/binding-linux-arm64-gnu@1.66.0'
  - '@oxlint/binding-linux-arm64-musl@1.66.0'
  - '@oxlint/binding-linux-ppc64-gnu@1.66.0'
  - '@oxlint/binding-linux-riscv64-gnu@1.66.0'
  - '@oxlint/binding-linux-riscv64-musl@1.66.0'
  - '@oxlint/binding-linux-s390x-gnu@1.66.0'
  - '@oxlint/binding-linux-x64-gnu@1.66.0'
  - '@oxlint/binding-linux-x64-musl@1.66.0'
  - '@oxlint/binding-openharmony-arm64@1.66.0'
  - '@oxlint/binding-win32-arm64-msvc@1.66.0'
  - '@oxlint/binding-win32-ia32-msvc@1.66.0'
  - '@oxlint/binding-win32-x64-msvc@1.66.0'
  - '@vue/language-core@3.3.1'
  - oxlint@1.66.0
  - vue-tsc@3.3.1
overrides:
  "vite": "npm:@voidzero-dev/vite-plus-core@latest"
  "vitest": "npm:@voidzero-dev/vite-plus-test@latest"
