import "./dept/dept.graphql.ts";
import "./menu/menu.graphql.ts";
import "./tenant/tenant.graphql.ts";
import "./usr/usr.graphql.ts";
import "./dict_detail/dict_detail.graphql.ts";
import "./dictbiz_detail/dictbiz_detail.graphql.ts";
import "./i18n/i18n.graphql.ts";
import "./options/options.graphql.ts";
import "./lang/lang.graphql.ts";
