// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AttDialog: typeof import('./../components/AttDialog.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElIconCircleCheck: typeof import('@element-plus/icons-vue')['CircleCheck']
    ElIconCircleClose: typeof import('@element-plus/icons-vue')['CircleClose']
    ElIconCirclePlus: typeof import('@element-plus/icons-vue')['CirclePlus']
    ElIconCopyDocument: typeof import('@element-plus/icons-vue')['CopyDocument']
    ElIconDelete: typeof import('@element-plus/icons-vue')['Delete']
    ElIconDownload: typeof import('@element-plus/icons-vue')['Download']
    ElIconEdit: typeof import('@element-plus/icons-vue')['Edit']
    ElIconExpand: typeof import('@element-plus/icons-vue')['Expand']
    ElIconFold: typeof import('@element-plus/icons-vue')['Fold']
    ElIconFullScreen: typeof import('@element-plus/icons-vue')['FullScreen']
    ElIconLock: typeof import('@element-plus/icons-vue')['Lock']
    ElIconRefresh: typeof import('@element-plus/icons-vue')['Refresh']
    ElIconSearch: typeof import('@element-plus/icons-vue')['Search']
    ElIconSetting: typeof import('@element-plus/icons-vue')['Setting']
    ElIconUnlock: typeof import('@element-plus/icons-vue')['Unlock']
    ElIconUpload: typeof import('@element-plus/icons-vue')['Upload']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSelectV2: typeof import('element-plus/es')['ElSelectV2']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    LinkAtt: typeof import('./../components/LinkAtt.vue')['default']
    LinkImage: typeof import('./../components/LinkImage.vue')['default']
    LinkList: typeof import('./../components/LinkList.vue')['default']
    ListSelectDialog: typeof import('./../components/ListSelectDialog.vue')['default']
    MyIframe: typeof import('./../components/MyIframe.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TableShowColumns: typeof import('./../components/TableShowColumns.vue')['default']
    UploadFileDialog: typeof import('./../components/UploadFileDialog.vue')['default']
    UploadImage: typeof import('./../components/UploadImage.vue')['default']
  }
}
